#ifndef __INCLUDE_GENERICPERIPHERALINTERFACES_STALECACHECALLBACK
#define __INCLUDE_GENERICPERIPHERALINTERFACES_STALECACHECALLBACK

class StaleCacheCallback {

    public:

        virtual void update() = 0;

};

#endif /* __INCLUDE_GENERICPERIPHERALINTERFACES_STALECACHECALLBACK */
