#ifndef __INCLUDE_ERRORHANDLING_ERRORCODEANDMESSAGE
#define __INCLUDE_ERRORHANDLING_ERRORCODEANDMESSAGE

enum I2C_ErrorCode {
    SUCCESS,
    TRANSMISSION_NOT_ACKNOWLEDGED,
    READ_TIMEOUT,
    UNKNOWN_FAILURE,
};

enum PWM_ErrorCode {
    SUCCESS,
    CONFIGURATION_FAILURE,
    UNKNOWN_FAILURE,
};

enum GlobalTimer_ErrorCode {
    SUCCESS,
    CONFIGURATION_FAILURE,
    UNKNOWN_FAILURE,
};

enum UART_ErrorCode {
    SUCCESS,
    CONFIGURATION_FAILURE,
    READ_TIMEOUT,
    UNKNOWN_FAILURE,
};

enum GPIO_ErrorCode {
    SUCCESS,
    CONFIGURATION_FAILURE,
    UNKNOWN_FAILURE,
};

#endif /* __INCLUDE_ERRORHANDLING_ERRORCODEANDMESSAGE */
